### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by vfscalfani** [xymaxim/marc2bib#8]
Hi, 

This looks like a really useful package! Could you consider adding a license file, so that I know what kind of reuse is allowed with marc2bib?

Thanks, 

Vin

**Comment by xymaxim** [comment]
Hi Vin, thank you for your suggestion. Glad you found the package interesting. 

Sorry for missing this out, it is MIT. I've added the license file to the repository. The updated version of the package will be uploaded to PyPI with the new release soon. Hope this will work for you.
